export const roleDefinitions = [
  {
    code: 'owner',
    name: 'Owner',
    description: 'The account owner with unrestricted access.',
  },
  {
    code: 'administrator',
    name: 'Administrator',
    description: 'Manage the lab workspace, people, and day-to-day operations.',
  },
  {
    code: 'developer',
    name: 'Developer',
    description: 'Access development and operational features without account-level controls.',
  },
] as const;

export const permissionDefinitions = [
  ['dashboard:view', 'dashboard', 'View dashboard'],
  ['cases:view', 'cases', 'View cases'],
  ['cases:create', 'cases', 'Create cases'],
  ['cases:update', 'cases', 'Update cases'],
  ['cases:delete', 'cases', 'Delete cases'],
  ['cases:approve', 'cases', 'Approve cases'],
  ['cases:move', 'cases', 'Move cases through production'],
  ['case_files:view', 'case_files', 'View case files'],
  ['case_files:upload', 'case_files', 'Upload case files'],
  ['case_files:download', 'case_files', 'Download case files'],
  ['case_files:delete', 'case_files', 'Delete case files'],
  ['case_activity:view', 'case_activity', 'View case activity'],
  ['case_activity:add_note', 'case_activity', 'Add case activity notes'],
  ['production_steps:view', 'production_steps', 'View production steps'],
  ['production_steps:assign', 'production_steps', 'Assign technicians'],
  ['production_steps:update', 'production_steps', 'Update production steps'],
  ['doctors:view', 'doctors', 'View doctors'],
  ['doctors:create', 'doctors', 'Create doctors'],
  ['doctors:update', 'doctors', 'Update doctors'],
  ['doctors:delete', 'doctors', 'Delete doctors'],
  ['doctors:revoke_access', 'doctors', 'Revoke doctor portal access'],
  ['clinics:view', 'clinics', 'View clinics'],
  ['clinics:create', 'clinics', 'Create clinics'],
  ['clinics:update', 'clinics', 'Update clinics'],
  ['clinics:delete', 'clinics', 'Delete clinics'],
  ['appliances:view', 'appliances', 'View appliances'],
  ['appliances:create', 'appliances', 'Create appliances'],
  ['appliances:update', 'appliances', 'Update appliances'],
  ['appliances:delete', 'appliances', 'Delete appliances'],
  ['appliances:activate', 'appliances', 'Activate appliances'],
  ['appliance_fields:view', 'appliance_fields', 'View appliance fields'],
  ['appliance_fields:create', 'appliance_fields', 'Create appliance fields'],
  ['appliance_fields:update', 'appliance_fields', 'Update appliance fields'],
  ['appliance_fields:delete', 'appliance_fields', 'Delete appliance fields'],
  ['workflows:view', 'workflows', 'View workflow templates'],
  ['workflows:create', 'workflows', 'Create workflow templates'],
  ['workflows:update', 'workflows', 'Update workflow templates'],
  ['workflows:delete', 'workflows', 'Delete workflow templates'],
  ['workflow_steps:create', 'workflow_steps', 'Create workflow steps'],
  ['workflow_steps:update', 'workflow_steps', 'Update workflow steps'],
  ['workflow_steps:delete', 'workflow_steps', 'Delete workflow steps'],
  ['workflow_steps:reorder', 'workflow_steps', 'Reorder workflow steps'],
  ['staff:view', 'staff', 'View staff'],
  ['staff:create', 'staff', 'Create staff'],
  ['staff:update', 'staff', 'Update staff'],
  ['staff:delete', 'staff', 'Delete staff'],
  ['staff:suspend', 'staff', 'Suspend staff access'],
  ['roles:view', 'roles', 'View roles'],
  ['roles:create', 'roles', 'Create roles'],
  ['roles:update', 'roles', 'Update roles'],
  ['roles:delete', 'roles', 'Delete roles'],
  ['roles:manage_permissions', 'roles', 'Manage role permissions'],
  ['lab_profile:view', 'lab_profile', 'View lab profile'],
  ['lab_profile:update', 'lab_profile', 'Update lab profile'],
  ['lab_profile:export', 'lab_profile', 'Export lab profile data'],
  ['lab_profile:manage_subscription', 'lab_profile', 'Manage subscription'],
  ['compliance_documents:view', 'compliance_documents', 'View compliance requirements'],
  ['compliance_documents:upload', 'compliance_documents', 'Upload compliance documents'],
  ['compliance_documents:replace', 'compliance_documents', 'Replace compliance documents'],
  ['lab_settings:view', 'lab_settings', 'View lab settings'],
  ['lab_settings:update', 'lab_settings', 'Update lab settings'],
  ['account:manage_owner', 'account', 'Manage account owner'],
  ['account:suspend', 'account', 'Suspend the lab account'],
  ['account:close', 'account', 'Close the lab account'],
  ['account:export', 'account', 'Export lab data'],
] as const;

export type SeedRoleCode = (typeof roleDefinitions)[number]['code'];
export type SeedPermissionCode = (typeof permissionDefinitions)[number][0];
